name: Keep Streamlit App Awake

on:
  schedule:
    - cron: '0 * * * *'  # Toutes les heures
  workflow_dispatch:      # Permet de lancer manuellement si besoin

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Streamlit app
        run: curl -s -o /dev/null -w "%{http_code}" https://clustering-tool.streamlit.app/
